name: karo_dogs
description: "Dog breeds with beautiful pictures"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.5.1
  flutter: 3.24.1

dependencies:
  cached_query_flutter: ^2.2.0
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  go_router: ^14.2.7
  json_annotation: ^4.9.0
  logging: ^1.2.0
  provider: ^6.1.2
  retrofit: ^4.4.1

dev_dependencies:
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  leancode_lint: ^14.1.0
  retrofit_generator: ^9.1.1

flutter:
  uses-material-design: true
